branch-defaults:
  master:
    environment: congo-production
  staging:
    environment: congo-dev
  stable_roger:
    environment: congo-staging
  integration:
    environment: congo-integration
global:
  application_name: congo
  default_ec2_keyname: grouphub-congo
  default_platform: 64bit Amazon Linux 2015.09 v2.0.4 running Ruby 2.2 (Puma)
  default_region: us-east-1
  profile: null
  sc: git
