branch-defaults:
  staging:
    environment: congo-staging
global:
  application_name: congo
  default_ec2_keyname: grouphub-congo
  default_platform: 64bit Amazon Linux 2014.09 v1.2.1 running Ruby 2.2 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
